// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB07eKFRTu2rnEFzAXfOzqMg0e7qrTrgA',
    appId: '1:62676164263:web:82bd7bfdc1737e5a3e4582',
    messagingSenderId: '62676164263',
    projectId: 'taskfy-3241c',
    authDomain: 'taskfy-3241c.firebaseapp.com',
    storageBucket: 'taskfy-3241c.firebasestorage.app',
    measurementId: 'G-L63NJL46Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlLjRk7y1I-DQpjulAF8JCW27T7nhCR6M',
    appId: '1:62676164263:android:8586163cf377e27d3e4582',
    messagingSenderId: '62676164263',
    projectId: 'taskfy-3241c',
    storageBucket: 'taskfy-3241c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6T_YcUZoiEMSG4R2DQOtXp0yfYELORl4',
    appId: '1:62676164263:ios:d3762f514181fc3a3e4582',
    messagingSenderId: '62676164263',
    projectId: 'taskfy-3241c',
    storageBucket: 'taskfy-3241c.firebasestorage.app',
    iosBundleId: 'com.example.taskfy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6T_YcUZoiEMSG4R2DQOtXp0yfYELORl4',
    appId: '1:62676164263:ios:d3762f514181fc3a3e4582',
    messagingSenderId: '62676164263',
    projectId: 'taskfy-3241c',
    storageBucket: 'taskfy-3241c.firebasestorage.app',
    iosBundleId: 'com.example.taskfy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB07eKFRTu2rnEFzAXfOzqMg0e7qrTrgA',
    appId: '1:62676164263:web:5e6c8d4fe37b68383e4582',
    messagingSenderId: '62676164263',
    projectId: 'taskfy-3241c',
    authDomain: 'taskfy-3241c.firebaseapp.com',
    storageBucket: 'taskfy-3241c.firebasestorage.app',
    measurementId: 'G-7KGFN2WRHD',
  );
}
